package com.chrynan.kapi.core

import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * Represents an API error response body. This loosely conforms to the
 * [RFC-7807 specification](https://www.rfc-editor.org/rfc/rfc7807).
 *
 * @property [type] A URI reference [RFC3986](https://www.rfc-editor.org/rfc/rfc3986) that identifies the problem type.
 * This specification encourages that, when de-referenced, it provides human-readable documentation for the problem
 * type (e.g., using HTML [W3C.REC-html5-20141028](https://www.rfc-editor.org/rfc/rfc7807#ref-W3C.REC-html5-20141028)).
 * When this member is not present, its value is assumed to be "about:blank". Accepts relative URIs. Consumers MUST use
 * the [type] as the primary identifier for the problem type. The [title] is advisory and included only for users who
 * are not aware of the semantics of the URI and do not have the ability to discover them (e.g., offline log analysis).
 * Consumers SHOULD NOT automatically dereference the type URI.
 * @property [title] A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to
 * occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see
 * [RFC7231, Section 3.4](https://www.rfc-editor.org/rfc/rfc7231#section-3.4)).
 * @property [status] The HTTP status code ([RFC7231 Section 6](https://www.rfc-editor.org/rfc/rfc7231#section-6))
 * generated by the origin server for this occurrence of the problem.
 * @property [details] A human-readable explanation specific to this occurrence of the problem. This should focus on
 * helping the client correct the issue, rather than giving debugging information. Clients should not parse the
 * [details] field for information.
 * @property [instance] A URI reference that identifies the specific occurrence of the problem. It may or may not yield
 * further information if de-referenced. Accepts relative URIs.
 * @property [timestamp] The [Instant] the error occurred.
 * @property [help] A URI reference to use to obtain more information about the error.
 * @property [signature] A message signature value that can be used to determine that the error is correct and hasn't
 * been tampered with.
 */
@Serializable
data class ApiError(
    @SerialName(value = "type") val type: String = "about:blank",
    @SerialName(value = "title") val title: String,
    @SerialName(value = "details") val details: String? = null,
    @SerialName(value = "status") val status: Int? = null,
    @SerialName(value = "instance") val instance: String? = null,
    @SerialName(value = "timestamp") val timestamp: Instant? = null,
    @SerialName(value = "help") val help: String? = null,
    @SerialName(value = "signature") val signature: String? = null
)
